/**
 * Resolve the real download URLs from the latest GitHub release.
 *
 * The installer filenames are generated by Tauri's bundler at build time and appear nowhere in the
 * product repository. Hard-coding them would work until the next release renamed one, and the
 * failure would be a download button leading to a 404 — the single worst link on a website.
 *
 * Two things fail the build rather than degrade:
 *
 *   - a platform with no asset. A "coming soon" card is a dead card asserting a plan.
 *   - `latest.json` disagreeing with the release tag. That manifest is what installed apps read to
 *     update themselves, and the product's own release workflow documents that confusing it cost
 *     three patch releases.
 *
 *   npm run fetch:releases
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, ".content", "releases.json");
const REPO = "brcampidelli/chimera-agent";

export interface Download {
  readonly platform: "windows" | "macos-arm64" | "macos-intel" | "linux-appimage" | "linux-deb";
  readonly name: string;
  readonly url: string;
  readonly bytes: number;
}

/**
 * One published release, as the blog renders it.
 *
 * `body` is the release note exactly as written on GitHub. It is not rewritten into a post: the
 * CHANGELOG and the release page already hold that text, and a third copy of one truth is three
 * things to keep in step.
 */
export interface ReleaseNote {
  readonly tag: string;
  readonly version: string;
  readonly name: string;
  readonly published: string;
  readonly url: string;
  readonly body: string;
  readonly prerelease: boolean;
}

export interface Releases {
  readonly tag: string;
  readonly version: string;
  readonly published: string;
  readonly url: string;
  readonly downloads: readonly Download[];
  readonly history: readonly ReleaseNote[];
}

interface Asset {
  name: string;
  browser_download_url: string;
  size: number;
}

/**
 * Which asset belongs to which platform.
 *
 * `.sig`, `*.app.tar.gz` and `latest.json` are updater artefacts, not human downloads, and are
 * excluded deliberately. The Linux entry is the AppImage, never the `.deb`: the updater applies
 * the AppImage, and mixing the two up is the exact mistake the release workflow warns about.
 */
const MATCHERS: { platform: Download["platform"]; test: (name: string) => boolean }[] = [
  { platform: "windows", test: (n) => n.endsWith(".exe") },
  { platform: "macos-arm64", test: (n) => /aarch64\.dmg$/.test(n) },
  { platform: "macos-intel", test: (n) => /(x64|x86_64)\.dmg$/.test(n) },
  { platform: "linux-appimage", test: (n) => n.endsWith(".AppImage") },
  { platform: "linux-deb", test: (n) => n.endsWith(".deb") },
];

export function pick(assets: readonly Asset[]): { downloads: Download[]; missing: string[] } {
  const downloads: Download[] = [];
  const missing: string[] = [];
  for (const { platform, test } of MATCHERS) {
    const asset = assets.find((a) => !a.name.endsWith(".sig") && test(a.name));
    if (!asset) {
      missing.push(platform);
      continue;
    }
    downloads.push({
      platform,
      name: asset.name,
      url: asset.browser_download_url,
      bytes: asset.size,
    });
  }
  return { downloads, missing };
}

async function main(): Promise<void> {
  const headers: Record<string, string> = { Accept: "application/vnd.github+json" };
  // A token lifts the anonymous rate limit. It is optional and never required — a build that only
  // works for people holding a credential is a build nobody else can reproduce.
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

  const response = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, { headers });
  if (!response.ok) {
    console.error(`releases: GitHub answered ${response.status} ${response.statusText}`);
    process.exit(1);
  }
  const release = (await response.json()) as {
    tag_name: string;
    published_at: string;
    html_url: string;
    assets: Asset[];
  };

  const { downloads, missing } = pick(release.assets);
  if (missing.length > 0) {
    console.error(`releases: ${release.tag_name} has no asset for ${missing.join(", ")}.`);
    console.error("A download page that says 'coming soon' is a dead card asserting a plan.");
    process.exit(1);
  }

  const manifest = release.assets.find((a) => a.name === "latest.json");
  if (manifest) {
    const latest = (await (await fetch(manifest.browser_download_url)).json()) as {
      version: string;
    };
    const expected = release.tag_name.replace(/^v/, "");
    if (latest.version !== expected) {
      console.error(
        `releases: latest.json says ${latest.version} but the release is ${expected}. ` +
          "Installed apps read that manifest to update themselves.",
      );
      process.exit(1);
    }
  }

  // The release notes the blog publishes. Prereleases are excluded: an `rc` is a test of the
  // release machinery, not an announcement, and GitHub already keeps it off `releases/latest`.
  const listed = (await (
    await fetch(`https://api.github.com/repos/${REPO}/releases?per_page=30`, { headers })
  ).json()) as {
    tag_name: string;
    name: string | null;
    body: string | null;
    published_at: string;
    html_url: string;
    prerelease: boolean;
    draft: boolean;
  }[];

  const history: ReleaseNote[] = listed
    .filter((r) => !r.draft && !r.prerelease && (r.body ?? "").trim().length > 0)
    .map((r) => ({
      tag: r.tag_name,
      version: r.tag_name.replace(/^v/, ""),
      name: (r.name ?? r.tag_name).trim(),
      published: r.published_at,
      url: r.html_url,
      body: (r.body ?? "").trim(),
      prerelease: r.prerelease,
    }));

  const payload: Releases = {
    tag: release.tag_name,
    version: release.tag_name.replace(/^v/, ""),
    published: release.published_at,
    url: release.html_url,
    downloads,
    history,
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`);
  console.log(
    `releases: ${release.tag_name} — ${downloads.length} downloads, ${history.length} release notes`,
  );
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/fetch-releases.ts")) {
  void main();
}
