/**
 * Resolve the real download URLs from the latest GitHub release.
 *
 * The installer filenames are generated by Tauri's bundler at build time and appear nowhere in the
 * product repository. Hard-coding them would work until the next release renamed one, and the
 * failure would be a download button leading to a 404 — the single worst link on a website.
 *
 * Two things fail the build rather than degrade:
 *
 *   - a platform with no asset. A "coming soon" card is a dead card asserting a plan.
 *   - `latest.json` disagreeing with the release tag. That manifest is what installed apps read to
 *     update themselves, and the product's own release workflow documents that confusing it cost
 *     three patch releases.
 *
 *   npm run fetch:releases
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, ".content", "releases.json");
// The last known good release notes, tracked in the repository. `.content/` is a build
// artefact and gitignored; this one has to survive a clone.
const SNAPSHOT = join(ROOT, "content", "releases-snapshot.json");
const REPO = "brcampidelli/chimera-agent";

export interface Download {
  readonly platform: "windows" | "macos-arm64" | "macos-intel" | "linux-appimage" | "linux-deb";
  readonly name: string;
  readonly url: string;
  readonly bytes: number;
}

/**
 * One published release, as the blog renders it.
 *
 * `body` is the release note exactly as written on GitHub. It is not rewritten into a post: the
 * CHANGELOG and the release page already hold that text, and a third copy of one truth is three
 * things to keep in step.
 */
export interface ReleaseNote {
  readonly tag: string;
  readonly version: string;
  readonly name: string;
  readonly published: string;
  readonly url: string;
  readonly body: string;
  readonly prerelease: boolean;
}

export interface Releases {
  readonly tag: string;
  readonly version: string;
  readonly published: string;
  readonly url: string;
  readonly downloads: readonly Download[];
  readonly history: readonly ReleaseNote[];
  /** A prerelease NEWER than the stable one above, when there is one. Absent otherwise. */
  readonly preview?: Preview;
}

/**
 * A release candidate, offered beside the stable download rather than instead of it.
 *
 * Prereleases are still kept out of `history` — an `rc` is a test of the release machinery, not an
 * announcement, and a blog post per candidate is noise. What changed is that people asked to try
 * one, and the only route was reading a GitHub tag. So it gets a card, clearly marked, and only
 * while it leads: once the stable of the same version ships, `newerThan` drops it and the section
 * disappears without anyone editing anything.
 */
export interface Preview {
  readonly tag: string;
  readonly version: string;
  readonly published: string;
  readonly url: string;
  readonly downloads: readonly Download[];
}

interface Asset {
  name: string;
  browser_download_url: string;
  size: number;
}

/** A release as the list endpoint returns it — and as `releases/tags/<tag>` returns it too. */
interface ListedRelease {
  tag_name: string;
  name: string | null;
  body: string | null;
  published_at: string;
  html_url: string;
  prerelease: boolean;
  draft: boolean;
}

/**
 * Which asset belongs to which platform.
 *
 * `.sig`, `*.app.tar.gz` and `latest.json` are updater artefacts, not human downloads, and are
 * excluded deliberately. The Linux entry is the AppImage, never the `.deb`: the updater applies
 * the AppImage, and mixing the two up is the exact mistake the release workflow warns about.
 */
const MATCHERS: { platform: Download["platform"]; test: (name: string) => boolean }[] = [
  { platform: "windows", test: (n) => n.endsWith(".exe") },
  { platform: "macos-arm64", test: (n) => /aarch64\.dmg$/.test(n) },
  { platform: "macos-intel", test: (n) => /(x64|x86_64)\.dmg$/.test(n) },
  { platform: "linux-appimage", test: (n) => n.endsWith(".AppImage") },
  { platform: "linux-deb", test: (n) => n.endsWith(".deb") },
];

export function pick(assets: readonly Asset[]): { downloads: Download[]; missing: string[] } {
  const downloads: Download[] = [];
  const missing: string[] = [];
  for (const { platform, test } of MATCHERS) {
    const asset = assets.find((a) => !a.name.endsWith(".sig") && test(a.name));
    if (!asset) {
      missing.push(platform);
      continue;
    }
    downloads.push({
      platform,
      name: asset.name,
      url: asset.browser_download_url,
      bytes: asset.size,
    });
  }
  return { downloads, missing };
}

/**
 * Fetch JSON, or fail saying what actually happened.
 *
 * The status check existed here, on the first of three calls, and the other two parsed whatever came
 * back. On 2026-08-12 the asset CDN answered `503 Service Unavailable` with an HTML page and the
 * build died on:
 *
 *     SyntaxError: Unexpected token '<', "<html><bod"... is not valid JSON
 *
 * which is true and useless. It names the shape of the reply and hides the only fact worth having —
 * an upstream was down — and it sends whoever reads it looking for a parsing bug that does not
 * exist. Every network hop in this file goes through here now, because a guard written once and not
 * given to its siblings is the same guard being absent.
 *
 * `what` is not decoration: the three calls fail for different reasons (rate limit, a missing asset,
 * a CDN blip) and the message has to say which one you are looking at.
 */
/**
 * How long to wait between attempts, and therefore how many there are.
 *
 * Three, spaced out. On 2026-08-12 this one request — the updater manifest, off the release CDN —
 * failed five times in a day, each time taking a whole build with it and each time succeeding on a
 * manual re-run seconds later. Written down as data because the right number is an observation, not
 * a preference: if the failures ever stop clustering like that, the number should change.
 *
 * Exported so the tests can pass zeros. A unit test that genuinely waits thirteen seconds is a unit
 * test people start skipping.
 */
export const RETRY_WAITS_MS = [1_000, 3_000, 9_000];

const sleep = (ms: number) => new Promise((done) => setTimeout(done, ms));

/**
 * A read whose failure is not fatal, because the caller has somewhere else to go.
 *
 * `getJson` ends the process, which is right for the installer asset and for `latest.json` — they
 * have no second route. The release history has three, so its reads report and step aside instead.
 */
async function tryJson<T>(
  url: string,
  what: string,
  headers: Record<string, string>,
): Promise<T | null> {
  try {
    const response = await fetch(url, { headers });
    if (!response.ok) {
      console.warn(`releases: ${what} answered ${response.status} ${response.statusText}.`);
      return null;
    }
    return (await response.json()) as T;
  } catch (cause) {
    console.warn(`releases: could not reach ${what} — ${(cause as Error).message}`);
    return null;
  }
}

export async function getJson<T>(
  url: string,
  what: string,
  headers?: Record<string, string>,
  waits: readonly number[] = RETRY_WAITS_MS,
): Promise<T> {
  // Only the transient classes are retried: a connection that never completed, and a 5xx. A 4xx is
  // a wrong token, a wrong repo or a rate limit — waiting nine seconds to be told the same thing
  // three times is worse than being told once, and it is the same misjudgement as telling someone
  // to re-run a build that cannot pass. A 200 that is not JSON is not retried either: that is
  // either an upstream serving something strange or an API that changed shape, and the second one
  // deserves to be looked at rather than slept through.
  for (let attempt = 0; ; attempt++) {
    // Read the wait first and let its absence be what defines "last". `attempt >= waits.length`
    // says the same thing, but only to a reader — the compiler still has to be told that indexing
    // an array can miss, and deriving the flag from the lookup means the two can never disagree.
    const wait = waits[attempt];
    const last = wait === undefined;
    const again = async (why: string): Promise<void> => {
      if (wait === undefined) return;
      console.error(`releases: ${what} — ${why}; retrying in ${wait / 1000}s`);
      await sleep(wait);
    };

    let response: Response;
    try {
      response = await fetch(url, headers ? { headers } : undefined);
    } catch (cause) {
      // A DNS failure or a dropped connection never reaches the status check at all.
      if (!last) {
        await again((cause as Error).message);
        continue;
      }
      console.error(`releases: could not reach ${what} — ${(cause as Error).message}`);
      console.error(`  ${url}`);
      console.error(`  Gave up after ${waits.length + 1} attempts. Usually transient — re-run the build.`);
      process.exit(1);
    }

    if (!response.ok) {
      // 5xx is theirs and retrying works; 4xx is ours and retrying does not. Saying which saves the
      // next person from re-running a build that cannot succeed.
      if (response.status >= 500 && !last) {
        await again(`${response.status} ${response.statusText}`);
        continue;
      }
      console.error(`releases: ${what} answered ${response.status} ${response.statusText}`);
      console.error(`  ${url}`);
      console.error(
        response.status >= 500
          ? `  An upstream outage, not a change here. Gave up after ${waits.length + 1} attempts — re-run the build.`
          : "  This will not fix itself on a re-run — check the token, the repo, and the rate limit.",
      );
      process.exit(1);
    }

    try {
      return (await response.json()) as T;
    } catch (cause) {
      console.error(`releases: ${what} returned 200 but not JSON — ${(cause as Error).message}`);
      console.error(`  ${url}`);
      process.exit(1);
    }
  }
}

/** `"0.48.0rc1"` -> `[0, 48, 0]`. The prerelease suffix is deliberately dropped: what decides
 *  whether a candidate still leads is its BASE version against the stable one. */
function base(version: string): [number, number, number] | null {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(version.replace(/^v/, ""));
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

/**
 * Is `candidate` a version ahead of `stable`?
 *
 * Equal bases answer NO, and that is the case that matters: `0.48.0rc1` and `0.48.0` share a base,
 * and once the stable ships the candidate is behind it in every sense that counts. Answering YES
 * there would leave a "try the preview" card advertising an older build for ever.
 */
export function newerThan(candidate: string, stable: string): boolean {
  const a = base(candidate);
  const b = base(stable);
  if (!a || !b) return false;
  for (let i = 0; i < 3; i++) {
    const left = a[i] ?? 0;
    const right = b[i] ?? 0;
    if (left !== right) return left > right;
  }
  return false;
}

/**
 * The newest prerelease that is ahead of the stable release, with its installers.
 *
 * Best-effort by construction, unlike everything else that produces a download link here. A missing
 * asset on the STABLE release fails the build, because a dead card on the main download path is the
 * worst link a site can have. A missing asset on a candidate means the release workflow is probably
 * still uploading, and taking the whole site down over an optional card would be the wrong trade —
 * so it is logged and skipped, and the next build picks it up.
 */
export async function findPreview(
  listed: readonly ListedRelease[],
  stableVersion: string,
  headers: Record<string, string>,
): Promise<Preview | null> {
  const candidate = listed
    .filter((r) => r.prerelease && !r.draft)
    .find((r) => newerThan(r.tag_name.replace(/^v/, ""), stableVersion));
  if (!candidate) return null;

  const full = await tryJson<{ assets: Asset[] }>(
    `https://api.github.com/repos/${REPO}/releases/tags/${candidate.tag_name}`,
    `the preview release ${candidate.tag_name}`,
    headers,
  );
  if (!full) return null;

  const { downloads, missing } = pick(full.assets);
  if (missing.length > 0) {
    console.warn(
      `releases: preview ${candidate.tag_name} has no asset for ${missing.join(", ")} — skipping it.`,
    );
    return null;
  }
  return {
    tag: candidate.tag_name,
    version: candidate.tag_name.replace(/^v/, ""),
    published: candidate.published_at,
    url: candidate.html_url,
    downloads,
  };
}

/** A release the blog will publish a page for: shipped, stable, and with something written on it. */
export function isPublishedStable(release: ListedRelease): boolean {
  return !release.draft && !release.prerelease && (release.body ?? "").trim().length > 0;
}

/** How many stable releases the history wants before it stops asking for more pages. */
const HISTORY_WANTED = 10;
/** GitHub's maximum, and the reason one page used to be nowhere near enough. */
const PAGE_SIZE = 100;
/** A ceiling, so a repository shaped unexpectedly walks 5 pages rather than for ever. */
const MAX_PAGES = 5;

/**
 * Walk the release index until enough STABLE releases are in hand.
 *
 * One page of thirty used to be the whole of it, which held for as long as a release cycle was
 * shorter than thirty releases. On 2026-08-25 it was not: `v0.48.0rc1` … `rc30` filled the page
 * exactly, the newest stable release fell off the end, and the history came back empty on a repo
 * whose API was answering perfectly. The build then failed with a message saying the problem was
 * upstream and the fix was to re-run — which cannot work, and it was followed once before anybody
 * read the filter.
 *
 * That is the mistake `getJson` above already refuses to make about 4xx, one level up.
 */
export async function collectListed(
  headers: Record<string, string>,
  read: (url: string, what: string, headers: Record<string, string>) => Promise<ListedRelease[] | null>,
): Promise<ListedRelease[]> {
  const all: ListedRelease[] = [];
  for (let page = 1; page <= MAX_PAGES; page++) {
    const batch =
      (await read(
        `https://api.github.com/repos/${REPO}/releases?per_page=${PAGE_SIZE}&page=${page}`,
        `the release list (page ${page})`,
        headers,
      )) ?? [];
    all.push(...batch);
    // A short page is the last page — asking for another spends a request to be told nothing.
    if (batch.length < PAGE_SIZE) break;
    if (all.filter(isPublishedStable).length >= HISTORY_WANTED) break;
  }
  return all;
}

async function main(): Promise<void> {
  const headers: Record<string, string> = { Accept: "application/vnd.github+json" };
  // A token lifts the anonymous rate limit. It is optional and never required — a build that only
  // works for people holding a credential is a build nobody else can reproduce.
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

  const release = await getJson<{
    tag_name: string;
    published_at: string;
    html_url: string;
    assets: Asset[];
  }>(`https://api.github.com/repos/${REPO}/releases/latest`, "the latest release", headers);

  const { downloads, missing } = pick(release.assets);
  if (missing.length > 0) {
    console.error(`releases: ${release.tag_name} has no asset for ${missing.join(", ")}.`);
    console.error("A download page that says 'coming soon' is a dead card asserting a plan.");
    process.exit(1);
  }

  const manifest = release.assets.find((a) => a.name === "latest.json");
  if (manifest) {
    // This is the one that fell over: not the API, the asset CDN.
    const latest = await getJson<{ version: string }>(
      manifest.browser_download_url,
      "the updater manifest (latest.json)",
    );
    const expected = release.tag_name.replace(/^v/, "");
    if (latest.version !== expected) {
      console.error(
        `releases: latest.json says ${latest.version} but the release is ${expected}. ` +
          "Installed apps read that manifest to update themselves.",
      );
      process.exit(1);
    }
  }

  // The release notes the blog publishes. Prereleases are excluded: an `rc` is a test of the
  // release machinery, not an announcement, and GitHub already keeps it off `releases/latest`.
  // Three routes to the release notes, tried in order, because on 2026-08-17 the first two went
  // down together: the index answered 200-with-an-empty-array from one network and 504 from the CI
  // runner, and `/releases/tags/<tag>` answered 504 as well. With no route, the build cannot pass —
  // and it fails on `generateStaticParams`, which names the wrong cause entirely.
  //
  // Every live read here is best-effort. `getJson` is kept for the installer asset and the updater
  // manifest, which have no second route and are meant to take the build down.
  let listed: ListedRelease[] = await collectListed(headers, tryJson);

  if (listed.length === 0) {
    console.warn("releases: no releases from the index — trying tags.");
    const tags =
      (await tryJson<{ name: string }[]>(
        `https://api.github.com/repos/${REPO}/tags?per_page=30`,
        "the tag list",
        headers,
      )) ?? [];
    const recovered: ListedRelease[] = [];
    for (const tag of tags.filter((candidate) => /^v?\d+\.\d+\.\d+$/.test(candidate.name))) {
      const one = await tryJson<ListedRelease>(
        `https://api.github.com/repos/${REPO}/releases/tags/${tag.name}`,
        `the release ${tag.name}`,
        headers,
      );
      if (one) recovered.push(one);
    }
    if (recovered.length > 0) {
      listed = recovered;
      console.warn(`  Recovered ${recovered.length} releases by tag.`);
    }
  }

  // Last resort: the copy in the repository. Release notes a day old are a blog missing its newest
  // release post — it self-heals on the next good build. That is a different class of wrong from a
  // stale download link, which is why the downloads above are never served from here.
  if (listed.length === 0 && existsSync(SNAPSHOT)) {
    const cached = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as ReleaseNote[];
    if (cached.length > 0) {
      console.warn(`releases: the API gave nothing — using the committed snapshot.`);
      console.warn(`  ${cached.length} notes, newest ${cached[0]?.tag}. Refresh it when the API is back.`);
      listed = cached.map((note) => ({
        tag_name: note.tag,
        name: note.name,
        body: note.body,
        published_at: note.published,
        html_url: note.url,
        prerelease: note.prerelease,
        draft: false,
      }));
    }
  }

  const history: ReleaseNote[] = listed
    .filter(isPublishedStable)
    .map((r) => ({
      tag: r.tag_name,
      version: r.tag_name.replace(/^v/, ""),
      name: (r.name ?? r.tag_name).trim(),
      published: r.published_at,
      url: r.html_url,
      body: (r.body ?? "").trim(),
      prerelease: r.prerelease,
    }));

  // Empty history is not a degraded site, it is a broken build with a misleading message. The
  // rest of this file already fails rather than ship a dead download card; the same applies to a
  // blog whose release pages have no tags to generate.
  if (history.length === 0) {
    // Two causes, opposite remedies. Saying "re-run" to the second one is how an afternoon gets
    // spent re-running a build that cannot pass, and it happened before this branch was split.
    if (listed.length > 0) {
      const rcs = listed.filter((r) => r.prerelease).length;
      console.error(
        `releases: the index answered with ${listed.length} releases and not one of them is a ` +
          `published stable release (${rcs} are prereleases).`,
      );
      console.error("  Re-running CANNOT change this. Either a stable release has to be published,");
      console.error(`  or the walk has to reach further back than ${MAX_PAGES} pages of ${PAGE_SIZE}.`);
    } else {
      console.error("releases: no release notes from the index or from tags.");
      console.error(`  https://api.github.com/repos/${REPO}/releases?per_page=${PAGE_SIZE}`);
      console.error("  Both routes empty means an upstream problem, not a change here — re-run the");
      console.error("  build. Publishing with no release pages would look like a deliberate edit.");
    }
    process.exit(1);
  }

  const stableVersion = release.tag_name.replace(/^v/, "");
  // Read from the list that was already fetched for the history — no extra hop unless a candidate
  // is actually there.
  const preview = await findPreview(listed, stableVersion, headers);

  const payload: Releases = {
    tag: release.tag_name,
    version: stableVersion,
    published: release.published_at,
    url: release.html_url,
    downloads,
    history,
    ...(preview ? { preview } : {}),
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`);
  console.log(
    `releases: ${release.tag_name} — ${downloads.length} downloads, ${history.length} release notes` +
      (preview ? `, preview ${preview.tag}` : ""),
  );
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/fetch-releases.ts")) {
  void main();
}
