/**
 * The site's colour, shadow and motion tokens are the app's tokens. Not "based on" them — the
 * same values, extracted from `apps/desktop/src/index.css`.
 *
 * A hand-copied palette rots because nobody notices: the app ships a new accent, the site keeps
 * the old one, and for months the two products are visibly different shades of the same brand
 * while everybody assumes they match. So this script regenerates the file and CI runs it with
 * `--check`, which fails on any divergence. Copying rots because it is silent; copying with a
 * test that fails is synchronisation.
 *
 * A published npm package would be the textbook answer and the wrong one here: it would require a
 * release of the product repo for every colour tweak, and the app — which owns the values — would
 * not even consume it.
 *
 *   pnpm sync:tokens          regenerate src/styles/tokens.generated.css
 *   pnpm verify:tokens        fail if the committed file is stale
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = resolve(HERE, "..");
const OUT = join(SITE_ROOT, "src", "styles", "tokens.generated.css");

const SOURCE_REL = join("apps", "desktop", "src", "index.css");

/** Where the product tree is. CI syncs it into `.content/chimera` at a pinned tag. */
export function resolveProductRoot(env: NodeJS.ProcessEnv = process.env): string {
  const explicit = env.CHIMERA_REPO;
  if (explicit) return resolve(explicit);
  const synced = join(SITE_ROOT, ".content", "chimera");
  if (existsSync(join(synced, SOURCE_REL))) return synced;
  return resolve(SITE_ROOT, "..", "Agent AI");
}

/**
 * Pull one `<selector> { … }` block out of a stylesheet by counting braces.
 *
 * A regex would be shorter and would break the first time a token's value contains a brace — and
 * `--elev` is already a multi-line list of shadow functions, so "the first time" is not
 * hypothetical.
 */
export function extractBlock(css: string, selector: string): string {
  const start = css.indexOf(selector);
  if (start === -1) throw new Error(`selector not found: ${selector}`);
  const open = css.indexOf("{", start);
  if (open === -1) throw new Error(`no block for: ${selector}`);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}") {
      depth--;
      if (depth === 0) return css.slice(open + 1, i);
    }
  }
  throw new Error(`unterminated block for: ${selector}`);
}

/** Custom-property declarations in source order. Comments and non-token rules are dropped. */
export function tokensFrom(block: string): string[] {
  const withoutComments = block.replace(/\/\*[\s\S]*?\*\//g, "");
  const declarations = withoutComments
    .split(";")
    .map((d) => d.replace(/\s+/g, " ").trim())
    .filter((d) => d.startsWith("--"));
  return declarations.map((d) => `${d};`);
}

export function render(css: string): string {
  const dark = tokensFrom(extractBlock(css, ":root {"));
  const light = tokensFrom(extractBlock(css, ':root[data-theme="light"]'));
  if (dark.length === 0 || light.length === 0) {
    throw new Error("extracted an empty token set — the source shape changed");
  }
  const indent = (lines: string[]) => lines.map((l) => `  ${l}`).join("\n");
  return [
    "/* GENERATED by scripts/sync-tokens.ts — do not edit.",
    ` * Source: ${SOURCE_REL.replace(/\\/g, "/")} in brcampidelli/chimera-agent.`,
    " * Run `npm run sync:tokens` to regenerate; CI fails if this file is stale.",
    " */",
    ":root {",
    indent(dark),
    "}",
    "",
    ':root[data-theme="light"] {',
    indent(light),
    "}",
    "",
  ].join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const root = resolveProductRoot();
  const source = join(root, SOURCE_REL);
  if (!existsSync(source)) {
    console.error(`chimera-agent not found at ${root}`);
    console.error("Set CHIMERA_REPO, or run the content sync first.");
    process.exit(2);
  }
  const next = render(readFileSync(source, "utf8"));
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";

  if (check) {
    if (current === next) {
      console.log("tokens: in sync");
      return;
    }
    console.error("tokens: STALE — the app's design system moved and the site did not.");
    console.error("Run `npm run sync:tokens` and commit the result.");
    process.exit(1);
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, next);
  console.log(current === next ? "tokens: unchanged" : `tokens: wrote ${OUT}`);
}

// Run only when invoked as a script. `import.meta.url === file://${argv[1]}` is the idiomatic
// check and it is wrong on Windows, where the drive letter and separators do not survive the
// round trip — so compare the basename instead.
if (process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/sync-tokens.ts")) main();
